const LOCAL_STORAGE_KEY = "quiz_questions";
const QUESTION_ID_PREFIX = "question_";
const QUESTION_CONTAINER_SUFFIX = "container_";
const QUESTION_DESCRIPTION_SUFFIX = "description_";
const QUESTION_CHOICE_SUFFIX = "choice_";
const QUESTION_CONTAINER_ID_PREFIX =
  QUESTION_ID_PREFIX + QUESTION_CONTAINER_SUFFIX;
const QUESTION_CHOICE_ID_PREFIX = QUESTION_ID_PREFIX + QUESTION_CHOICE_SUFFIX;
const QUESTION_DESCRIPTION_ID_PREFIX =
  QUESTION_ID_PREFIX + QUESTION_DESCRIPTION_SUFFIX;

const QUESTION_CONTAINER_CLASSNAME = "question_container";
const QUESTION_CHOICE_CLASSNAME = "question_choice";
const QUESTION_DESCRIPTION_CLASSNAME = "question_description";
const CORRECT_CHOICE_CLASSNAME = "correct";
const INCORRECT_CHOICE_CLASSNAME = "incorrect";
const QUESTION_HEADER_CLASSNAME = "question_header"

const QUIZ_ROOT_DIV_ID = "quiz_root_div";
const QUIZ_ANCHOR_DIV_ID = "quiz_anchor_div";
const ADD_BTN_ID = "add_btn";
const SAVE_BTN_ID = "save_btn";
const DELETE_BTN_ID = "delete_btn";
const SUBMIT_BTN_ID = "submit_btn";

const SHOW_DIV_CLASSNAME = "show";
const ERROR_MSG_DIV_ID = "error_msg";
const CONTROL_DIV_ID = "control_div";
const HIDE_DIV_CLASSNAME = "hide";
const MARKS_DIV_ID = "marks_div";


export {
  LOCAL_STORAGE_KEY,
  QUESTION_ID_PREFIX,
  QUESTION_CONTAINER_ID_PREFIX,
  QUESTION_CHOICE_ID_PREFIX,
  QUESTION_DESCRIPTION_ID_PREFIX,
  QUESTION_CONTAINER_CLASSNAME,
  QUESTION_CHOICE_CLASSNAME,
  QUESTION_DESCRIPTION_CLASSNAME,
  QUIZ_ROOT_DIV_ID,
  CORRECT_CHOICE_CLASSNAME,
  INCORRECT_CHOICE_CLASSNAME,
  QUIZ_ANCHOR_DIV_ID,
  ADD_BTN_ID,
  SAVE_BTN_ID,
  DELETE_BTN_ID,
  QUESTION_HEADER_CLASSNAME,
  SUBMIT_BTN_ID,
  SHOW_DIV_CLASSNAME,
  ERROR_MSG_DIV_ID,
  CONTROL_DIV_ID,
  HIDE_DIV_CLASSNAME,
  MARKS_DIV_ID,
};
